name: release
on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    permissions:
      contents: write # To publish the release.
      id-token: write # To federate for the GPG key.

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: git fetch --prune --unshallow
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: false

      # This is provisioned here: https://github.com/chainguard-dev/secrets/blob/main/terraform-provider-oci.tf
      - uses: google-github-actions/auth@8254fb75a33b976a221574d287e93919e6a36f70 # v2.1.6
        id: auth
        with:
          workload_identity_provider: "projects/12758742386/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-provider-oci@chainguard-github-secrets.iam.gserviceaccount.com"
      - uses: google-github-actions/setup-gcloud@6189d56e4096ee891640bb02ac264be376592d6a # v2.1.2
        with:
          project_id: "chainguard-github-secrets"
      - uses: google-github-actions/get-secretmanager-secrets@0eee3cd066acdd9427a820bd68231cdea7c66a8d # v2.2.1
        id: secrets
        with:
          secrets: |-
            token:chainguard-github-secrets/terraform-provider-oci-signing-key

      - id: import_gpg
        uses: crazy-max/ghaction-import-gpg@cb9bde2e2525e640591a934b1fd28eef1dcaf5e5 # v6.2.0
        with:
          gpg_private_key: ${{ steps.secrets.outputs.token }}

      - uses: goreleaser/goreleaser-action@9ed2f89a662bf1735a48bc8557fd212fa902bebf # v6.1.0
        with:
          version: latest
          args: release --clean
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
